# Generated by Django 2.2.1 on 2019-06-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_url', models.TextField()),
                ('product_price', models.CharField(max_length=255)),
                ('all_time_low', models.CharField(max_length=255)),
            ],
        ),
    ]
