# Generated by Django 2.2.1 on 2019-06-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_url', models.TextField()),
                ('product_price', models.CharField(max_length=255)),
                ('all_time_low', models.CharField(max_length=255)),
                ('image_url', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
